### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by tenji240** [tenji240/RPG#25]
- [ ] Battle UI and Components
- [ ] Coversation UI and Components
- [ ] Traversal UI and Components
